name: Generate Release
run-name: Generate Release ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Major base'
        required: true
        default: '1.x'
        type: choice
        options:
          - 1.x
          - 2.x
      minor:
        description: 'Minor version'
        required: true
        type: number
      patch:
        description: 'Patch version'
        required: true
        type: number

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check version fits in 1.x
        if: inputs.target == '1.x'
        env:
          minor: ${{ fromJSON(inputs.minor) }}
          patch: ${{ fromJSON(inputs.patch) }}
        run: echo  Version is 1.$minor.$patch
      - name: Check vesrion fits in 2.x
        if: inputs.target == '2.x'
        env:
          minor: ${{ fromJSON(inputs.minor) }}
          patch: ${{ fromJSON(inputs.patch) }}
        run: echo  Version is 2.$minor.$patch
