name: Generate Release
run-name: Generate Release ${{ fromJSON(inputs.major) }}.${{ fromJSON(inputs.minor) }}.${{ fromJSON(inputs.patch) }}

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
      minor:
        description: 'Minor version'
        required: true
        type: number
      patch:
        description: 'Patch version'
        required: true
        type: number

jobs:
  print-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      version: ${{ fromJSON(inputs.major) }}.${{ fromJSON(inputs.minor) }}.${{ fromJSON(inputs.patch) }}
      branch: ${{ inputs.major == 2 && 'develop' || 'develop_1.x' }}
      target: ${{ inputs.major == 2 && 'main' || 'main_1.x' }}
    steps:
      - name: Check minor has no decimals
        run: ${{ !contains(fromJSON(inputs.minor), '.') }}
        
      - name: Check patch has no decimals
        run: ${{ !contains(fromJSON(inputs.patch), '.') }}

      - name: Checkout ${{ env.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.branch }}
      
      - name: Update version in txt file
        run: |
          rm ./mambaSharedFramework/Resources/version.txt
          echo $version > ./mambaSharedFramework/Resources/version.txt
          git diff
        
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Bump version to ${{ env.version }}
          branch: release/${{ env.version }}
          base: ${{ env.taget }}
