name: Generate Release
run-name: Generate Release ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Release base'
        required: true
        default: '1.x'
        type: choice
        options:
          - 1.x
          - 2.x
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check version fits in 1.x
        if: inputs.target == '1.x'
        run: echo  Need to check if ${{ inputs.version }} is in 1.x
      - name: Check vesrion fits in 2.x
        if: inputs.target == '2.x'
        run: echo  Need to check if ${{ inputs.version }} is in 2.x
