name: Generate Release
run-name: Generate Release ${{ fromJSON(inputs.major) }}.${{ fromJSON(inputs.minor) }}.${{ fromJSON(inputs.patch) }}

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
      minor:
        description: 'Minor version'
        required: true
        type: number
      patch:
        description: 'Patch version'
        required: true
        type: number

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check minor has no decimals
        run: ${{ !contains(fromJSON(inputs.minor), '.') }}
      - name: Check patch has no decimals
        run: ${{ !contains(fromJSON(inputs.patch), '.') }}
      - name: Print version
        env:
          version: ${{ fromJSON(inputs.major) }}.${{ fromJSON(inputs.minor) }}.${{ fromJSON(inputs.patch) }}
        run: echo  Version is $version
