name: Release
run-name: Release ${{ inputs.tags }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Release base'
        required: true
        default: '1.x'
        type: choice
        options:
          - 1.x
          - 2.x
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: echo  The version is ${{ inputs.version }}
