name: Context testing
on:
  push:
    branches:
      - 'main'
      - 'main_1.x'

jobs:
  get-version:
    name: Get version for release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: version
        run: echo "version=`cat ./mambaSharedFramework/Resources/version.txt`" >> "$GITHUB_OUTPUT"

  log-version:
    name: Log the version for release
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Log version
        run: echo ${{ needs.get-version.outputs.version }}
